sonar.projectName=Mycelium IoT V2
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8

sonar.sources=src,public
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.exclusions=dist/**,node_modules/**,coverage/**,reports/**,public/photos/**
sonar.coverage.exclusions=src/cli/**,public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
